
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: hello-world-persistent-data
  name: hello-world-persistent-data
  namespace: 1-test
spec:
  host: hello-world-persistent-data-1-test.apps.ocp1.demolab.es
  port:
    targetPort: 8080-tcp
  to:
    kind: Service
    name: hello-world-persistent-data
    weight: 100

---

apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    alpha.image.policy.openshift.io/resolve-names: '*'
    deployment.kubernetes.io/revision: "2"
    image.openshift.io/triggers: '[{"from":{"kind":"ImageStreamTag","name":"hello-world-persistent-data:latest","namespace":"1-test"},"fieldPath":"spec.template.spec.containers[?(@.name==\"hello-world-persistent-data\")].image"}]'
    openshift.io/generated-by: OpenShiftWebConsole
  labels:
    app: hello-world-persistent-data
  name: hello-world-persistent-data
  namespace: 1-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-world-persistent-data
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: hello-world-persistent-data
        deploymentconfig: hello-world-persistent-data
    spec:
      containers:
      - image: pablogarciaarevalo/hello-world-persistent-data:latest
        imagePullPolicy: Always
        name: hello-world-persistent-data
        ports:
        - containerPort: 8080
          protocol: TCP
        - containerPort: 8888
          protocol: TCP
        volumeMounts:
          - name: my-pvc-nfs
            mountPath: /data
      volumes:
      - name: my-pvc-nfs
        persistentVolumeClaim:
          claimName: pvc-rwm

---

apiVersion: v1
kind: Service
metadata:
  annotations:
    openshift.io/generated-by: OpenShiftWebConsole
  labels:
    app: hello-world-persistent-data
  name: hello-world-persistent-data
  namespace: 1-test
spec:
  clusterIP: 172.30.48.9
  ports:
  - name: 8080-tcp
    port: 8080
    protocol: TCP
    targetPort: 8080
  - name: 8888-tcp
    port: 8888
    protocol: TCP
    targetPort: 8888
  selector:
    app: hello-world-persistent-data
    deploymentconfig: hello-world-persistent-data
  sessionAffinity: None
  type: ClusterIP



