kind: Pod
apiVersion: v1
metadata:
  name: hello-world-rwm
spec:
  volumes:
    - name: task-pv-storage
      persistentVolumeClaim:
       claimName: pvc-rwm
  containers:
    - name: task-pv-container
      image: pablogarciaarevalo/hello-world-persistent-data:latest
      command:
        - /bin/sh
        - "-c"
        - "sleep 60m"
      volumeMounts:
        - mountPath: "/data"
          name: task-pv-storage
          resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"

