apiVersion: template.openshift.io/v1
kind: Template
labels:
  template: hello-world-persistent-data-example
message: |-
  The following service(s) have been created in your project: ${NAME}.

  For more information about using this template, including OpenShift considerations, see https://github.com/pablogarciaarevalo/hello-world-persistent-data/blob/master/README.md.
metadata:
  annotations:
    description: A hello world HTTP server example using persistent data. For more information 
      about using this template, including OpenShift considerations, 
      see https://github.com/pablogarciaarevalo/hello-world-persistent-data/blob/master/README.md.
    iconClass: icon-linux
    openshift.io/display-name: Hello world HTTP server using persistent data
    openshift.io/documentation-url: https://github.com/pablogarciaarevalo/hello-world-persistent-data
    openshift.io/long-description: This template defines resources needed to develop
      a hello world HTTP server.
    openshift.io/provider-display-name: Pablo Garcia Arevalo
    tags: quickstart,hello-world
  labels:
    samples.operator.openshift.io/managed: "true"
  name: hello-world-persistent-data-example
objects:
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      description: Exposes and load balances the application pods
    name: ${NAME}
  spec:
    ports:
    - name: web
      port: 8080
      targetPort: 8080
    selector:
      name: ${NAME}
- apiVersion: v1
  kind: Route
  metadata:
    annotations:
      template.openshift.io/expose-uri: http://{.spec.host}{.spec.path}
    name: ${NAME}
  spec:
    host: ${APPLICATION_DOMAIN}
    to:
      kind: Service
      name: ${NAME}
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: ${NAME}
  spec:
    accessModes:
      - ${PVC_ACCESS_MODE}
    resources:
      requests:
        storage: ${PVC_SIZE}
    storageClassName: ${PVC_STORAGE_CLASS}
- apiVersion: v1
  kind: Deployment
  metadata:
    annotations:
      description: Defines how to deploy the application server
      template.alpha.openshift.io/wait-for-ready: "true"
    name: ${NAME}
  spec:
    replicas: 1
    selector:
      name: ${NAME}
    strategy:
      type: Rolling
    template:
      metadata:
        labels:
          name: ${NAME}
        name: ${NAME}
      spec:
        containers:
        - env: []
          image: pablogarciaarevalo/hello-world-persistent-data:latest
          name: hello-world-pod
          ports:
          - containerPort: 8080
            protocol: TCP
          volumeMounts:
            - name: my-pvc-nfs
              mountPath: /data
        volumes:
        - name: my-pvc-nfs
          persistentVolumeClaim:
            claimName: pvc-rwm
parameters:
- description: The name assigned to all of the objects defined in this template.
  displayName: Name
  name: NAME
  required: true
  value: hello-world-example
- description: The exposed hostname that will route to the hello world service, if left
    blank a value will be defaulted.
  displayName: Application Hostname
  name: APPLICATION_DOMAIN
- description: The name of the PVC
  name: PVC_NAME
  required: true
- description: The PVC access mode (RWO, ROX, RWX)
  name: PVC_ACCESS_MODE
  required: true
  value: ReadWriteMany
- description: The requested minimum volume capacity.
  name: PVC_SIZE
  required: true
- description: The requested storage class to use
  name: PVC_STORAGE_CLASS
  required: true
  value: nas
